---
title: Trabalho de Conclusão de Curso
---

Esta página descreve como é o processo de construção do TCC sob minha orientação.

## Informações Gerais

Os TCCs que oriento são no formato desenvolvimento de **protótipo** (maioria) ou **artigo científico**. Embora artigos sejam mais curtos, eles devem ser publicáveis para que o projeto seja aprovado.

O TCC foi pensado para ser desenvolvido em dois semestres:

- **TCC-1:** estudo dos conceitos necessários para o desenvolvimento do projeto, escrita do código-fonte e  realização de experimentos computacionais.
- **TCC-2:** escrita da monografia e apresentação (defesa) de projeto. Por padrão, o código não é mais modificado neste semestre.

O acompanhamento do projeto é realizado por comunicação eletrônica e **reuniões semanais (presenciais ou remotas) com duração de 30min**. Dependendo do andamento do projeto, as reuniões podem se tornar quinzenais.

## Documentos Importantes

Os procedimentos para aprovação nas disciplinas são ligeiramente diferentes dependendo do curso. As páginas abaixo descrevem os artefatos que devem ser construídos e seus prazos de entrega.

- [Ciência da Computação](https://informatica.ufes.br/pt-br/graduacao/ccomp/projeto-de-gradua%C3%A7%C3%A3o).
- [Engenharia da Computação](https://informatica.ufes.br/pt-br/trabalho-de-conclusao-de-curso)
- Engenharia Elétrica: Os professores das disciplinas disponibilizam documentos contendo as regras.

**Importante**: É sua responsabilidade garantir que todos os artefatos sejam produzidos e que os prazos sejam cumpridos. Sugiro adicionar lembretes no google agenda e manter a lista de artefatos em um local de fácil acesso.

[Templates em Latex](https://github.com/vitorsouza/latex-templates/tree/main) para o relatório de TCC-1 e para a monografia de TCC-2 foram criados e disponibilizados pelo Prof. Vitor Souza.

Para começar a escrever, faça o download do repositório. coloque a pasta contendo o seu template de interesse em um arquivo .zip e faça o upload para o sistema [Prism](https://prism.openai.com/). O Prism é uma alternativa grátis ao Overleaf. Por fim, compartilhe o projeto comigo.

## Passo a Passo

Abaixo é descrito o algoritmo para concluir as disciplinas de TCC.

### TCC-1

1. Definir o tema junto com o orientador.
   1. *Critério de pronto*: tema definido.
2. Definir o cronograma de entregáveis cobrindo as fases de estudo, desenvolvimento de código-fonte, realização de experimentos e escrita de relatório de protótipo.
   1. *Critério de pronto*: cronograma feito.
3. Estudar os conceitos fundamentais para o projeto.
   1. *Critério de pronto*: entrega de repositório contendo códigos de exemplo demonstrando que conhecimentos foram adquiridos.
4. Ler e sumarizar artigos relacionados ao tema.
   1. *Critério de pronto*: entrega dos resumos dos trabalhos relacioandos.
5. Implementar o código e realizar experimentos.
   1. *Critério de pronto*: repositório com código para realização dos experimentos, além de tabelas e gráficos de resultados.
6. Escrita do relatório de protótipo
   1. *Critério de pronto*:  entrega do relatório escrito e revisado.

### TCC-2

1. Escrever introdução (~ 2 semanas).
1. Escrever referencial teórico (~ 3 semanas).
1. Escrever desenvolvimento (~ 1 mês).
1. Escrever avaliação experimental (~ 1 mês).
1. Escrever conclusão e resumo (~ 1 semana).
1. Realizar revisão do texto (~ 2 semanas).
1. Definir os membros e agendar a banca de defesa de TCC. Neste momento, o texto deve estar pronto para ser enviado para a banca.
1.  Preparar e realizar apresentação.

## Definindo o Tema do TCC

Um bom tema de TCC cumpre os seguintes critérios:

- **Poderia trazer benefícios para um grupo de pessoas**: tornar processos mais eficientes ou mais acurados, viabilizar novas aplicações, trazer novas informações sobre fenômenos.
- **Requer o uso do conhecimento de várias disciplinas do curso**.
- **Equivale a um semestre de trabalho**: Uma boa analogia é pensar na quantidade média de trabalho e nível de dificuldade para fazer os trabalhos de uma disciplina de programação.

O TCC **não** precisa ser gigante, revolucionário ou mudar o mundo.


## Trabalhos Relacionados

Na seção de trabalhos relacionados, você deve descrever **5-8 artigos** que abordaram o mesmo tema do seu projeto. O orientador vai te recomendar 1-3 artigos de referência. Os demais você deverá identificar usando o algoritmo abaixo.

### Identificando Artigos para Trabalhos Relacionados

Com base no que você aprendeu lendo estes artigos de referência, faça buscas de palavras-chave no [google scholar](https://scholar.google.com.br/). Avalie pelo título se os artigos são relacionados ao seu tópico de interese. Abra os artigos relevantes em novas abas para olhar depois.


::: {.callout-tip}
## Outras formas de encontrar artigos relevantes

Os artigos citados por bons artigos tendem a ser bons artigos. As referências utilizadas nos artigos indicados por seu orientador são uma fonte de trabalhos relacionados. Você também pode buscar os artigos indicados no google scholar e verificar os artigos que citaram eles.
:::

O próximo passo é selecionar um subconjunto de 5 artigos para analisar com mais calma.

**Importante:** Valide com o seu orientador se os artigos são de fato relevantes antes de lê-los para evitar desperdício de energia.

- Itere sobre as abas abertas, leia o resumo e confirme se o trabalho é próximo ao que você está fazendo. Se não, feche a aba.
- Dê preferência para artigos recentes (últimos 3-5 anos) , com muitas citações (10+) e/ou que tenham sido publicados em boas conferências e periódicos.
- Saber quais conferências e periódicos são bons requer um pouco de experiência, mas uma heurística é  buscar seu nome na [aba metrics do google scholar](https://scholar.google.com.br/citations?view_op=top_venues&hl=pt-BR) e verificar o índice H5. Veículos com índices H5 maiores que 40, em geral, são bons.
- Na área de IA, exemplos de boas conferências são CVPR, ICLR, NeurIPS e ICML. Na área de robótica, temos ICRA e IROS. Exemplos de bons periódicos da área de IA são IEEE Transactions on Pattern Analysis and Machine Intelligence, IEEE Transactions on Neural Networks and Learning Systems e Nature Machine Intelligence.

Se ao final da filtragem você não conseguir identificar 5 artigos, repita o processo fazendo usando novas palavras chave.

### Lendo Trabalhos Relacionados

Para cada artigo relacionado, você deve escrever um parágrafo descrevendo os seguintes itens:

- Qual foi a principal contribuição do artigo? O que ele trouxe de novo?
- Como é o método proposto? O que ele tem de melhor que os métodos anteriores^?
- Como foi feita a avaliação experimental?  Quais bases de dados e métricas foram usadas? Qual procedimento foi adotado?
- Quais foram os principais resultados? Quais os valores das métricas?
- Quais limitações existem no trabalho? Idealmente, seu estudo deve superar estas limitações.

::: {.callout-tip}
## Identifique coisas reutilizáveis ao ler os artigos

Fique atento a argumentos utilizados na introdução, dicas de como calibrar hiperparâmetros, como obter o máximo de modelos, cuidados na realização de experimentos e análises críticas de outros trabalhos da literatura. Frequentemente, os artigos te ajudarão a implementar e escrever seu trabalho. Lembre-se, contudo, que você não deve copiar e colar trechos de texto porque isto é plágio e punível com a morte (de sua carreira acadêmica).
:::

**Exemplo 1 (trabalho de identificação de doenças em exames de raio-X do pulmão):** "*Narin  et  al.  (2021)  avaliaram  três  arquiteturas  de  redes neurais (ResNet50, InceptionV3 e Inception-ResNetV2) na tarefa de identificação de doenças a partir de imagens de Raio-X de pulmão. A ResNet50 alcançou 98% de acurácia, o melhor valor dentre os modelos comparados.  A rede foi treinada e avaliada com exames de pessoas saudáveis ou com COVID-19. Casos de pneumonia não foram incluídos nos experimentos*".

**Exemplo 2 (trabalho de mapeamento para veículos autônomos):** "*Wolcott e Eustice (2017) propuseram um método probabilístico de localização que modela o mundo como um mapa multirresolução de misturas de gaussianas. Seus mapas de mistura de gaussianas representam a distribuição de altura e intensidade de refletância do ambiente medida por scanners LiDAR (Velodyne HDL-32E). Um algoritmo de localização baseado no Filtro de Kalman Estendido (EKF) é utilizado para estimar a pose do carro por meio do registro de nuvens de pontos 3D em relação aos mapas multirresolução de mistura de gaussianas. O método foi avaliado em dois carros autônomos sob condições climáticas adversas e apresentou erros de estimativa de localização de aproximadamente 0,15 m.*"

## Escrevendo a Introdução

A introdução é um argumento lógico que tem como objetivo:

- motivar e justificar o investimento de recursos (tempo, energia, etc.) no projeto, e
-  dar uma visão geral do que foi feito para a pessoa decidir se quer continuar lendo o texto ou não.

A motivação e a justificativa são feitas explicando:

- por que o tópico do trabalho é relevante;
- por que soluções existentes não resolvem o problema (se existisse uma solução que você conseguisse instalar e rodar em 5min, você não precisaria ter feito o projeto, concorda?).

### Estrutura da Introdução

**1-3 parágrafos:** Explicação de porque o tópico é relevante. Traga estatísticas e números que expliquem o impacto da área.

**1-3 parágrafos:** Descrição de como outros trabalhos abordaram o problema e porque estas soluções são insuficientes. Depois de escrever a seção de trabalhos relacionados, fica fácil escrever estes parágrafos. Basta resumir e fazer uma análise crítica.

**1-2 parágrafo:** Resumo do que você fez, como foi a metodologia experimental e os principais resultados. Começa com "Portanto, este trabalho propõe (...)".

**[Opcional] Contribuições:** Listagem (tipicamente em bullet points) das principais contribuições do trabalho. Começa com "Com isto, as principais contribuições deste trabalho são: (...)". É mais comum em artigos enviados para periódicos.

**[Opcional] Organização do Trabalho:** Descrição do que é explicado nas próximas seções ou capítulos do trabalho. A introdução não é mencionada. Cada seção ou capítulo é descrito em uma frase. Segue a estrutura "O trabalho está organizado como indicado a seguir. O capítulo 2 descreve os conceitos fundamentais para compreender o trabalho. O capítulo 3 traz o sistema proposto e como suas etapas são implementadas. (...)". Nos TCCs, existe uma seção específica para isto na introdução.

